CREATE DATABASE IF NOT EXISTS `covid_dw`;
USE covid_dw;

CREATE TABLE IF NOT EXISTS `county_cases_daily` (
	county_date_key INT NOT NULL AUTO_INCREMENT,
	county_key VARCHAR(5) NOT NULL,
	date_key INT NOT NULL,
	county_date_id VARCHAR(13) NOT NULL,
	positives_new SMALLINT NOT NULL DEFAULT 0,
	deaths_new SMALLINT NOT NULL DEFAULT 0,
	positives_total INT NOT NULL DEFAULT 0,
	deaths_total INT NOT NULL DEFAULT 0,
	positives_ma7d FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d FLOAT NOT NULL DEFAULT 0,
	positives_ma14d FLOAT NOT NULL DEFAULT 0,
	deaths_ma14d FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lag7 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lag7 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lag14 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lag14 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lead7 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lead7 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lead14 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lead14 FLOAT NOT NULL DEFAULT 0,
	PRIMARY KEY (county_date_key),
	UNIQUE KEY (county_date_id),
	UNIQUE KEY (county_key, date_key),
	INDEX county_cases_daily_county_date_key_idx (county_date_key),
	INDEX county_cases_daily_county_key_date_key_idx (county_key, date_key),
	INDEX county_cases_daily_date_key_idx (date_key)
);

CREATE TABLE IF NOT EXISTS `state_cases_daily` (
	state_date_key INT NOT NULL AUTO_INCREMENT,
	state_key VARCHAR(5) NOT NULL,
	date_key INT NOT NULL,
	positives_new INT NOT NULL DEFAULT 0,
	deaths_new INT NOT NULL DEFAULT 0,
	positives_total INT NOT NULL DEFAULT 0,
	deaths_total INT NOT NULL DEFAULT 0,
	positives_ma7d FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d FLOAT NOT NULL DEFAULT 0,
	positives_ma14d FLOAT NOT NULL DEFAULT 0,
	deaths_ma14d FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lag7 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lag7 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lag14 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lag14 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lead7 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lead7 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lead14 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lead14 FLOAT NOT NULL DEFAULT 0,
	PRIMARY KEY (state_date_key),
	UNIQUE KEY (state_key, date_key),
	INDEX state_cases_daily_state_date_key_idx (state_date_key),
	INDEX state_cases_daily_state_key_date_key_idx (state_key, date_key),
	INDEX state_cases_daily_date_key_idx (date_key)
);

CREATE TABLE IF NOT EXISTS `csa_cases_daily` (
	csa_date_key INT NOT NULL AUTO_INCREMENT,
	csa_key VARCHAR(5) NOT NULL,
	date_key INT NOT NULL,
	positives_new INT NOT NULL DEFAULT 0,
	deaths_new INT NOT NULL DEFAULT 0,
	positives_total INT NOT NULL DEFAULT 0,
	deaths_total INT NOT NULL DEFAULT 0,
	positives_ma7d FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d FLOAT NOT NULL DEFAULT 0,
	positives_ma14d FLOAT NOT NULL DEFAULT 0,
	deaths_ma14d FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lag7 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lag7 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lag14 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lag14 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lead7 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lead7 FLOAT NOT NULL DEFAULT 0,
	positives_ma7d_lead14 FLOAT NOT NULL DEFAULT 0,
	deaths_ma7d_lead14 FLOAT NOT NULL DEFAULT 0,
	PRIMARY KEY (csa_date_key),
	UNIQUE KEY (csa_key, date_key),
	INDEX csa_cases_daily_csa_date_key_idx (csa_date_key),
	INDEX csa_cases_daily_csa_key_date_key_idx (csa_key, date_key),
	INDEX csa_cases_daily_date_key_idx (date_key)
);
