USE covid_dw;

TRUNCATE TABLE `dim_date`;
INSERT INTO `dim_date` (
	date_key,
	date,
	timestamp,
	day_suffix,
	day_name,
	day_of_week,
	day_of_month,
	day_of_year,
	week_of_year,
	month,
	month_name,
	month_name_abbrev,
	quarter,
	year,
	first_day_of_week,
	last_day_of_week,
	first_day_of_month,
	last_day_of_month,
	first_day_of_year,
	last_day_of_year,
	yyyyww,
	yyyymm,
	holiday_name,
	holiday_flag,
	weekend_flag
)
SELECT
	date_id AS date_key,
	date,
	timestamp,
	day_suffix,
	day_name,
	day_of_week,
	day_of_month,
	day_of_year,
	week_of_year,
	month,
	month_name,
	month_name_abbrev,
	quarter,
	year,
	first_day_of_week,
	last_day_of_week,
	first_day_of_month,
	last_day_of_month,
	first_day_of_year,
	last_day_of_year,
	yyyyww,
	yyyymm,
	holiday_name,
	holiday_flag,
	weekend_flag
FROM covid.`date`;